"""
Planes nutricionales curados para la API de nutrición.
"""
from app.schemas.nutrition import NutritionMealPlan, NutritionPlanResponse


PUBLIC_NUTRITION_GUIDELINE_PLANS = [
    NutritionPlanResponse(
        id="myplate-balanced",
        name="Plan Balanceado MyPlate",
        description="Plato equilibrado con frutas, verduras, granos integrales, proteinas magras y lacteos o alternativas fortificadas.",
        recommendedGoal="Rutina diaria equilibrada y educacion alimentaria general.",
        caloriesTarget=1860,
        proteinTarget=95,
        carbsTarget=226,
        fatTarget=64,
        mealsPerDay=4,
        macroDistribution={"protein": 22, "carbs": 50, "fat": 28},
        source="USDA MyPlate",
        difficulty="Facil",
        tag="Balanceado",
        generalRecommendation="Prioriza variedad, porciones consistentes y agua durante el dia.",
        meals=[
            NutritionMealPlan(id="myplate-balanced-breakfast", name="Desayuno", description="Avena con fruta, yogur natural o bebida fortificada y semillas.", calories=430, protein=20, carbs=62, fat=12),
            NutritionMealPlan(id="myplate-balanced-lunch", name="Almuerzo", description="Verduras, arroz integral, pollo o menestras y una fruta.", calories=650, protein=34, carbs=82, fat=20),
            NutritionMealPlan(id="myplate-balanced-dinner", name="Cena", description="Pescado, tortilla o tofu con verduras y papa/camote.", calories=560, protein=32, carbs=58, fat=22),
            NutritionMealPlan(id="myplate-balanced-snack", name="Snack", description="Fruta con frutos secos o queso fresco.", calories=220, protein=9, carbs=24, fat=10),
        ],
        recommendedFoods=["Verduras", "Frutas", "Granos integrales", "Legumbres", "Pescado", "Huevos", "Yogur natural"],
        foodsToModerate=["Bebidas azucaradas", "Frituras", "Postres altos en azucar", "Embutidos"],
    ),
    NutritionPlanResponse(
        id="dash-heart",
        name="Plan DASH Saludable",
        description="Patron alto en frutas, verduras, granos integrales y legumbres, con sodio moderado.",
        recommendedGoal="Cuidar habitos cardiovasculares y mejorar calidad general de la dieta.",
        caloriesTarget=1780,
        proteinTarget=91,
        carbsTarget=218,
        fatTarget=58,
        mealsPerDay=4,
        macroDistribution={"protein": 20, "carbs": 52, "fat": 28},
        source="NHLBI DASH Eating Plan",
        difficulty="Intermedio",
        tag="Corazon",
        generalRecommendation="Reduce gradualmente sodio, salsas saladas y productos muy procesados.",
        meals=[
            NutritionMealPlan(id="dash-heart-breakfast", name="Desayuno", description="Pan integral con palta, fruta y yogur bajo en grasa.", calories=390, protein=18, carbs=56, fat=11),
            NutritionMealPlan(id="dash-heart-lunch", name="Almuerzo", description="Bowl de quinoa, lentejas, verduras, aceite de oliva y fruta.", calories=620, protein=28, carbs=86, fat=18),
            NutritionMealPlan(id="dash-heart-dinner", name="Cena", description="Pescado al horno con ensalada grande y camote.", calories=560, protein=35, carbs=54, fat=20),
            NutritionMealPlan(id="dash-heart-snack", name="Snack", description="Yogur natural con frutos rojos o frutos secos sin sal.", calories=210, protein=10, carbs=22, fat=9),
        ],
        recommendedFoods=["Frutas", "Verduras", "Legumbres", "Granos integrales", "Lacteos bajos en grasa"],
        foodsToModerate=["Sal agregada", "Embutidos", "Salsas altas en sodio", "Comida rapida"],
    ),
    NutritionPlanResponse(
        id="mediterranean",
        name="Plan Mediterraneo",
        description="Verduras, frutas, legumbres, cereales integrales, pescado, aceite de oliva y frutos secos.",
        recommendedGoal="Energia sostenida, variedad alimentaria y habitos flexibles.",
        caloriesTarget=1950,
        proteinTarget=93,
        carbsTarget=208,
        fatTarget=80,
        mealsPerDay=4,
        macroDistribution={"protein": 20, "carbs": 45, "fat": 35},
        source="Dietary Guidelines y patron Mediterraneo",
        difficulty="Facil",
        tag="Energia",
        generalRecommendation="Usa aceite de oliva en porciones moderadas y combina legumbres o pescado con vegetales.",
        meals=[
            NutritionMealPlan(id="mediterranean-breakfast", name="Desayuno", description="Yogur natural con fruta, avena y nueces.", calories=440, protein=21, carbs=48, fat=18),
            NutritionMealPlan(id="mediterranean-lunch", name="Almuerzo", description="Ensalada de garbanzos con verduras, aceite de oliva y pan integral.", calories=650, protein=26, carbs=78, fat=25),
            NutritionMealPlan(id="mediterranean-dinner", name="Cena", description="Pescado con verduras asadas y arroz integral.", calories=620, protein=38, carbs=58, fat=24),
            NutritionMealPlan(id="mediterranean-snack", name="Snack", description="Fruta con almendras o hummus con vegetales.", calories=240, protein=8, carbs=24, fat=13),
        ],
        recommendedFoods=["Aceite de oliva", "Pescado", "Legumbres", "Verduras", "Frutas", "Frutos secos"],
        foodsToModerate=["Carnes procesadas", "Dulces frecuentes", "Mantequilla en exceso"],
    ),
    NutritionPlanResponse(
        id="moderate-high-protein",
        name="Plan Alto en Proteinas",
        description="Proteina de calidad distribuida durante el dia, con carbohidratos y grasas saludables.",
        recommendedGoal="Recuperacion, saciedad y apoyo a entrenamiento recreativo.",
        caloriesTarget=2080,
        proteinTarget=142,
        carbsTarget=192,
        fatTarget=75,
        mealsPerDay=4,
        macroDistribution={"protein": 30, "carbs": 40, "fat": 30},
        source="Guias alimentarias publicas y datos nutricionales abiertos",
        difficulty="Intermedio",
        tag="Proteina",
        generalRecommendation="Reparte proteinas en cada comida y acompana con vegetales y carbohidratos integrales.",
        meals=[
            NutritionMealPlan(id="moderate-high-protein-breakfast", name="Desayuno", description="Huevos o tofu revuelto con pan integral y fruta.", calories=470, protein=32, carbs=42, fat=18),
            NutritionMealPlan(id="moderate-high-protein-lunch", name="Almuerzo", description="Pollo, pescado o tempeh con arroz integral y verduras.", calories=700, protein=48, carbs=70, fat=22),
            NutritionMealPlan(id="moderate-high-protein-dinner", name="Cena", description="Menestras con huevo, queso fresco o tofu y ensalada.", calories=610, protein=40, carbs=52, fat=24),
            NutritionMealPlan(id="moderate-high-protein-snack", name="Snack", description="Yogur griego, fruta y frutos secos.", calories=300, protein=22, carbs=28, fat=11),
        ],
        recommendedFoods=["Huevos", "Pescado", "Pollo", "Tofu", "Tempeh", "Yogur griego", "Legumbres"],
        foodsToModerate=["Suplementos innecesarios", "Carnes procesadas", "Barras altas en azucar"],
    ),
    NutritionPlanResponse(
        id="moderate-low-carb",
        name="Plan Bajo en Carbohidratos moderado",
        description="Reduce carbohidratos refinados sin eliminarlos, priorizando alimentos frescos.",
        recommendedGoal="Control de antojos y carbohidratos de mejor calidad.",
        caloriesTarget=1910,
        proteinTarget=119,
        carbsTarget=112,
        fatTarget=102,
        mealsPerDay=4,
        macroDistribution={"protein": 28, "carbs": 32, "fat": 40},
        source="Guias alimentarias publicas",
        difficulty="Intermedio",
        tag="Moderado",
        generalRecommendation="Evita restricciones extremas; usa frutas, legumbres o granos integrales en porciones adecuadas.",
        meals=[
            NutritionMealPlan(id="moderate-low-carb-breakfast", name="Desayuno", description="Omelette con verduras, queso fresco y fruta pequena.", calories=430, protein=28, carbs=24, fat=24),
            NutritionMealPlan(id="moderate-low-carb-lunch", name="Almuerzo", description="Ensalada grande con pollo, palta, menestras pequenas y aceite de oliva.", calories=670, protein=42, carbs=38, fat=35),
            NutritionMealPlan(id="moderate-low-carb-dinner", name="Cena", description="Pescado o tofu con verduras y porcion pequena de camote.", calories=560, protein=36, carbs=32, fat=28),
            NutritionMealPlan(id="moderate-low-carb-snack", name="Snack", description="Yogur natural o frutos secos con fruta en porcion moderada.", calories=250, protein=13, carbs=18, fat=15),
        ],
        recommendedFoods=["Verduras", "Huevos", "Pescado", "Pollo", "Tofu", "Palta", "Aceite de oliva"],
        foodsToModerate=["Pan blanco", "Dulces", "Jugos", "Cereales azucarados"],
    ),
    NutritionPlanResponse(
        id="balanced-vegetarian",
        name="Plan Vegetariano Balanceado",
        description="Legumbres, tofu, huevos o lacteos si aplica, frutos secos, cereales integrales, frutas y verduras.",
        recommendedGoal="Alimentacion vegetariana variada con proteina distribuida.",
        caloriesTarget=1990,
        proteinTarget=97,
        carbsTarget=235,
        fatTarget=72,
        mealsPerDay=4,
        macroDistribution={"protein": 22, "carbs": 50, "fat": 28},
        source="Guias alimentarias publicas y patrones vegetarianos",
        difficulty="Facil",
        tag="Vegetariano",
        generalRecommendation="Incluye proteina en cada comida y presta atencion a hierro, calcio, B12 y omega-3.",
        meals=[
            NutritionMealPlan(id="balanced-vegetarian-breakfast", name="Desayuno", description="Avena con bebida fortificada, fruta, chia y mantequilla de mani.", calories=480, protein=20, carbs=62, fat=18),
            NutritionMealPlan(id="balanced-vegetarian-lunch", name="Almuerzo", description="Lentejas con arroz integral, ensalada y palta.", calories=680, protein=30, carbs=92, fat=20),
            NutritionMealPlan(id="balanced-vegetarian-dinner", name="Cena", description="Tofu salteado o tortilla con verduras y quinoa.", calories=590, protein=34, carbs=56, fat=24),
            NutritionMealPlan(id="balanced-vegetarian-snack", name="Snack", description="Yogur, queso fresco o hummus con vegetales.", calories=240, protein=13, carbs=25, fat=10),
        ],
        recommendedFoods=["Legumbres", "Tofu", "Huevos", "Lacteos o alternativas fortificadas", "Frutos secos"],
        foodsToModerate=["Ultraprocesados vegetarianos", "Postres frecuentes", "Frituras"],
    ),
]


def get_plan(plan_id: str) -> NutritionPlanResponse | None:
    return next((plan for plan in PUBLIC_NUTRITION_GUIDELINE_PLANS if plan.id == plan_id), None)
